name: pytorch_env
channels:
  - pytorch
  - anaconda
  - defaults
dependencies:
  - _tflow_select=2.3.0=gpu
  - absl-py=0.12.0=py38haa95532_0
  - aiohttp=3.6.3=py38he774522_0
  - argon2-cffi=20.1.0=py38h2bbff1b_1
  - astor=0.8.1=py38haa95532_0
  - astunparse=1.6.3=py_0
  - async-timeout=3.0.1=py38haa95532_0
  - async_generator=1.10=pyhd3eb1b0_0
  - attrs=21.2.0=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - bleach=3.3.0=pyhd3eb1b0_0
  - blinker=1.4=py38haa95532_0
  - brotlipy=0.7.0=py38h2bbff1b_1003
  - ca-certificates=2020.10.14=0
  - cachetools=4.2.2=pyhd3eb1b0_0
  - certifi=2020.6.20=py38_0
  - cffi=1.14.5=py38hcd4344a_0
  - chardet=3.0.4=py38haa95532_1003
  - click=8.0.1=pyhd3eb1b0_0
  - colorama=0.4.4=pyhd3eb1b0_0
  - coverage=5.5=py38h2bbff1b_2
  - cryptography=3.4.7=py38h71e12ea_0
  - cudatoolkit=11.0.221=h74a9793_0
  - cython=0.29.23=py38hd77b12b_0
  - decorator=4.4.2=py_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - entrypoints=0.3=py38_0
  - freetype=2.10.4=hd328e21_0
  - gast=0.4.0=py_0
  - google-auth=1.31.0=pyhd3eb1b0_0
  - google-auth-oauthlib=0.4.4=pyhd3eb1b0_0
  - google-pasta=0.2.0=py_0
  - grpcio=1.36.1=py38hc60d5dd_1
  - hdf5=1.10.4=h7ebc959_0
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=58.2=ha925a31_3
  - idna=2.10=pyhd3eb1b0_0
  - importlib-metadata=3.10.0=py38haa95532_0
  - importlib_metadata=3.10.0=hd3eb1b0_0
  - intel-openmp=2021.2.0=haa95532_616
  - ipykernel=5.3.4=py38h5ca1d4c_0
  - ipython=7.22.0=py38hd4e2768_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.6.3=pyhd3eb1b0_1
  - jedi=0.17.0=py38_0
  - jinja2=3.0.0=pyhd3eb1b0_0
  - jpeg=9b=hb83a4c4_2
  - jsonschema=3.2.0=py_2
  - jupyter=1.0.0=py38_7
  - jupyter_client=6.1.12=pyhd3eb1b0_0
  - jupyter_console=6.4.0=pyhd3eb1b0_0
  - jupyter_core=4.7.1=py38haa95532_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
  - keras-applications=1.0.8=py_1
  - keras-preprocessing=1.1.2=pyhd3eb1b0_0
  - libpng=1.6.37=h2a8f88b_0
  - libprotobuf=3.14.0=h23ce68f_0
  - libsodium=1.0.18=h62dcd97_0
  - libtiff=4.2.0=hd0e1b90_0
  - libuv=1.40.0=he774522_0
  - lz4-c=1.9.3=h2bbff1b_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markdown=3.3.4=py38haa95532_0
  - markupsafe=2.0.1=py38h2bbff1b_0
  - mistune=0.8.4=py38he774522_1000
  - mkl=2021.2.0=haa95532_296
  - mkl-service=2.3.0=py38h2bbff1b_1
  - mkl_fft=1.3.0=py38h277e83a_2
  - mkl_random=1.2.1=py38hf11a4ad_2
  - msys2-conda-epoch=20160418=1
  - multidict=4.7.6=py38he774522_1
  - nbclient=0.5.3=pyhd3eb1b0_0
  - nbconvert=6.0.7=py38_0
  - nbformat=5.1.3=pyhd3eb1b0_0
  - nest-asyncio=1.5.1=pyhd3eb1b0_0
  - ninja=1.10.2=h6d14046_1
  - notebook=6.4.0=py38haa95532_0
  - numpy-base=1.20.2=py38hc2deb75_0
  - oauthlib=3.1.0=py_0
  - olefile=0.46=py_0
  - openssl=1.1.1k=h2bbff1b_0
  - opt_einsum=3.3.0=pyhd3eb1b0_1
  - packaging=20.9=pyhd3eb1b0_0
  - pandoc=2.12=haa95532_0
  - pandocfilters=1.4.3=py38haa95532_1
  - parso=0.8.2=pyhd3eb1b0_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=8.2.0=py38h4fa10fc_0
  - pip=21.1.2=py38haa95532_0
  - prometheus_client=0.11.0=pyhd3eb1b0_0
  - prompt-toolkit=3.0.17=pyh06a4308_0
  - prompt_toolkit=3.0.17=hd3eb1b0_0
  - protobuf=3.14.0=py38hd77b12b_1
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.8=py_0
  - pycparser=2.20=py_2
  - pygments=2.9.0=pyhd3eb1b0_0
  - pyjwt=1.7.1=py38_0
  - pyopenssl=20.0.1=pyhd3eb1b0_1
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pyqt=5.9.2=py38ha925a31_4
  - pyreadline=2.1=py38_1
  - pyrsistent=0.17.3=py38he774522_0
  - pysocks=1.7.1=py38haa95532_0
  - python=3.8.10=hdbf39b2_7
  - python-dateutil=2.8.1=pyhd3eb1b0_0
  - pytorch=1.7.1=py3.8_cuda110_cudnn8_0
  - pywin32=227=py38he774522_1
  - pywinpty=0.5.7=py38_0
  - pyzmq=20.0.0=py38hd77b12b_1
  - qt=5.9.7=vc14h73c81de_0
  - qtconsole=5.1.0=pyhd3eb1b0_0
  - qtpy=1.9.0=py_0
  - requests=2.25.1=pyhd3eb1b0_0
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - send2trash=1.5.0=pyhd3eb1b0_1
  - setuptools=52.0.0=py38haa95532_0
  - sip=4.19.13=py38ha925a31_0
  - six=1.16.0=pyhd3eb1b0_0
  - sqlite=3.35.4=h2bbff1b_0
  - tensorboard=2.4.0=pyhc547734_0
  - tensorboard-plugin-wit=1.6.0=py_0
  - tensorflow=2.3.0=mkl_py38h8557ec7_0
  - tensorflow-base=2.3.0=eigen_py38h75a453f_0
  - tensorflow-estimator=2.5.0=pyh7b7c402_0
  - tensorflow-gpu=2.3.0=he13fc11_0
  - termcolor=1.1.0=py38haa95532_1
  - terminado=0.9.4=py38haa95532_0
  - testpath=0.4.4=pyhd3eb1b0_0
  - tk=8.6.10=he774522_0
  - torchaudio=0.7.2=py38
  - torchvision=0.8.2=py38_cu110
  - tornado=6.1=py38h2bbff1b_0
  - traitlets=5.0.5=pyhd3eb1b0_0
  - typing_extensions=3.7.4.3=pyha847dfd_0
  - urllib3=1.26.4=pyhd3eb1b0_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wcwidth=0.2.5=py_0
  - webencodings=0.5.1=py38_1
  - werkzeug=1.0.1=pyhd3eb1b0_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - widgetsnbextension=3.5.1=py38_0
  - win_inet_pton=1.1.0=py38haa95532_0
  - wincertstore=0.2=py38_0
  - winpty=0.4.3=4
  - wrapt=1.12.1=py38he774522_1
  - xz=5.2.5=h62dcd97_0
  - zeromq=4.3.3=ha925a31_3
  - zipp=3.4.1=pyhd3eb1b0_0
  - zlib=1.2.11=h62dcd97_4
  - zstd=1.4.9=h19a0ad4_0
  - pip:
    - albumentations==1.0.0
    - anykeystore==0.2
    - contextlib2==0.6.0.post1
    - cycler==0.10.0
    - deprecated==1.2.12
    - et-xmlfile==1.1.0
    - filelock==3.0.12
    - fsspec==2021.6.1
    - future==0.18.2
    - gdown==3.13.0
    - greenlet==1.1.0
    - h5py==3.3.0
    - humanize==3.10.0
    - hupper==1.10.3
    - imageio==2.9.0
    - imgaug==0.4.0
    - joblib==1.0.1
    - keras==2.4.3
    - kiwisolver==1.3.1
    - kornia==0.5.4
    - lightning-bolts==0.3.4
    - littleutils==0.2.2
    - mako==1.1.4
    - matplotlib==3.4.2
    - medcam==0.1.21
    - medpy==0.4.0
    - ml-collections==0.1.0
    - monai==0.6.0
    - networkx==2.5.1
    - nibabel==3.2.1
    - numpy==1.19.0
    - opencv-python==4.5.2.54
    - opencv-python-headless==4.5.2.54
    - openpyxl==3.0.7
    - outdated==0.2.1
    - pandas==1.2.4
    - pandas-flavor==0.2.0
    - pastedeploy==2.1.1
    - patsy==0.5.1
    - pbkdf2==1.3
    - pingouin==0.3.12
    - plaster==1.0
    - plaster-pastedeploy==0.7
    - pydeprecate==0.3.0
    - pydicom==2.1.2
    - pynrrd==0.4.2
    - pyramid==2.0
    - pyramid-mailer==0.15.1
    - python3-openid==3.2.0
    - pytorch-lightning==1.3.8
    - pytorch-model-summary==0.1.2
    - pytz==2021.1
    - pywavelets==1.1.1
    - pyyaml==5.4.1
    - repoze-sendmail==4.4.1
    - ruamel-yaml-clib==0.2.6
    - scikit-image==0.18.1
    - scikit-learn==0.24.2
    - scipy==1.6.3
    - seaborn==0.11.1
    - shapely==1.7.1
    - simpleitk==1.2.4
    - sklearn==0.0
    - sqlalchemy==1.4.19
    - statannot==0.2.3
    - statsmodels==0.12.2
    - tabulate==0.8.9
    - threadpoolctl==2.1.0
    - tifffile==2021.6.14
    - torchio==0.18.45
    - torchmetrics==0.4.1
    - torchsummary==1.5.1
    - torchsummaryx==1.3.0
    - tqdm==4.61.1
    - transaction==3.0.1
    - translationstring==1.4
    - velruse==1.1.1
    - venusian==3.0.0
    - webob==1.8.7
    - wtforms==2.3.3
    - wtforms-recaptcha==0.3.2
    - xarray==0.18.2
    - xlrd==2.0.1
    - yarl==1.5.1
    - zope-deprecation==4.4.0
    - zope-interface==5.4.0
    - zope-sqlalchemy==1.4
prefix: C:\Users\sulai\anaconda3\envs\pytorch_env
